language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-4.6-multilib gcc-multilib libc6-dev-i386 lib32z1-dev
script: make gtest-bootstrap && make && make test

